{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f1a96b24_350b841d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 49
      },
      "lineNbr": 0,
      "author": {
        "id": 1000018
      },
      "writtenOn": "2022-12-13T14:36:26Z",
      "side": 1,
      "message": "DONT push anything yet, lets other commit fixing the CI failure goes in first. ",
      "revId": "f381e953d769cc43ccfd412e8da9d52ae4acff54",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}